title:            Pulse Code
description:      Ben Coleman
logo:             logo.png
disqus_shortname: pulse-code
reading_time:     false
words_per_minute: 180
url: 

excerpt_separator: <!--more-->

# Owner/author information
owner:
  name:           Ben Coleman
  avatar:         about/profile.png
  bio:            "Application developer and all round technology geek. Currently a Cloud Solution Architect at Microsoft"
  email:          benc.uk@gmail.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:        BenCodeGeek
  github:         benc-uk
  linkedin:       benc-uk

# Background image to be tiled on all pages
#background: bg/Quantum-Gradient.svg

# Analytics and webmaster tools stuff goes here
google_analytics:   
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

timezone:    Etc/GMT0
future:      false  # publish future dated posts --  true, false (default) 
highlighter: rouge
markdown:    kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:categories/:title/

# Amount of post to show on home page
paginate: 6

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

include: 
  - .htaccess
  - pages
exclude: 
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
  - vendor
  - _site
  - _ignore
  - "**/node_modules"

defaults:
  - scope:
      path: ""
    values:
      image:
        feature: header/h07.svg
  - scope:
      path: "" 
      type: posts
    values:
      layout: post       
